name: Test Examples

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule: # Run tests once a week to detect regressions
    - cron: '0 0 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Get Python version
        run: |
          PYTHON_VERSION=$(cat pyproject.toml | grep "requires-python" | grep -Eo "[0-9]+\.[0-9]+")
          echo "PYTHON_VERSION=${PYTHON_VERSION}" >> $GITHUB_ENV

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo DEBIAN_FRONTEND=noninteractive apt-get -y install mpi mpich libmpich-dev libopenmpi-dev
          pip install .[full]

      - name: Run examples
        run: |
          find examples/ -name '*.py' -not -name '*mpi*' | \
            xargs -I {} sh -c "echo '{}': && python '{}' && echo ''"

      - name: Run MPI examples
        run: |
          lamboot
          find examples/ -name '*.py' -name '*mpi*' | \
            xargs -I {} sh -c "echo '{}': && mpirun -np 2 --oversubscribe python '{}' && echo ''"
          lamhalt
